First content
knowledge-club/ruby pull request #2
Opened 2016-10-12 03:25 UTC by OdineiRibeiro

@darlanmendonca and @khaosdoctor, take a look, please!

Just a articles about installation...

2016-10-13 00:50 UTC, khaosdoctor requested changes
There are some changes to be made, I think we'd better discuss the idea of creating two separate README files...

2016-10-13 00:50 UTC, khaosdoctor commented on README.md
> +puts "Hello World!"
I don't think this code block is actually needed...

2016-10-13 00:50 UTC, khaosdoctor commented on README.md
> +## Getting started
Will it be a topic structure? Or it is just the initial parts only?

2016-10-13 00:50 UTC, khaosdoctor commented on README.md
> +*Olá! Aqui falamos português também!*<br>
I think this should be moved to an quote right on top of the document. The first thing a Brazilian user has to see is this...

However I'm not comfortable with the idea of creating 2 separated readme files

2016-10-13 00:50 UTC, khaosdoctor commented on contents/en/404_en.md
> +Sorry, the page you are looking for is still being written! Enquanto Meanwhile, take a look at our [README](../../README.md), has lots of cool stuff there!
"Enquanto"

2016-10-13 00:50 UTC, khaosdoctor commented on contents/en/how_to_install_on_windows.md
> +Unlike [Ubuntu](como_instalar_no_ubuntu.md) and [MacOS](como_instalar_no_macos.md), install Ruby on Windows don't need a version manager, you'll just need a wizard just like any other Windows softwar
Filenames are in portuguese?

2016-10-13 00:50 UTC, khaosdoctor commented on contents/pt_br/como_instalar_no_macos.md
> +- É tãããããão fácil! Dê uma olhada em como fazer essa instalação no [Ubuntu](how_to_install_on_ubuntu.md) e compare!
I think the file links are mistaken, the english files are pointing to portuguese ones and vice versa

2016-10-13 11:00 UTC, OdineiRibeiro commented
@khaosdoctor, I carried away. I remade the file structure and now it's more simple and easy to use and maintain

2016-10-17 11:35 UTC, OdineiRibeiro commented
@khaosdoctor, I'll merge these changes. If you want request anything more, open an issue please :D

2016-10-17 11:35 UTC, merged